### ISSUE TITLE
微信支付bug

### ISSUE THREAD

**Issue by penghu6** [essensoft/paylinks#158]
![bug](https://github.com/essensoft/paylink/assets/145628717/13fb9544-cee5-488b-bacc-dd9a5bff04ae)

.net6 项目实现微信支付遇到上图截图bug，
服务器：centos7
docker 容器 
  var model = new WeChatPayTransactionsJsApiBodyModel
  {
      AppId = _optionsAccessor.Value.AppId,
      MchId = _optionsAccessor.Value.MchId,
      Amount = new Amount { Total = total, Currency = "CNY" },
      Description = config.Title,
      NotifyUrl = “”,
      OutTradeNo = orderNo,
      Payer = new PayerInfo { OpenId = jsCode2JsonResult.openid }
  };
  linux 环境读取证书解析bug
 证书配置参数：  "Certificate": "cert\\apiclient_cert.p12",
 windows 环境正常

**Comment by roc916** [comment]
想多了，单纯没找到证书文件，当base64字符串处理了。
建议检查证书文件位置
https://github.com/essensoft/paylink/blob/dev/src/Essensoft.Paylink.WeChatPay/WeChatPayOptions.cs#L159-L166

**Comment by penghu6** [comment]
好的，在检查代码看看
