### ISSUE TITLE
Essensoft.Paylink.WeChatPay.V3 IWeChatPayClient少一个声明

### ISSUE THREAD

**Issue by saixin** [essensoft/paylinks#159]
IWeChatPayClient少一个声明
Task<T> ExecuteAsync<T>(IWeChatPayPrivacyGetRequest<T> request, WeChatPayOptions options) where T : WeChatPayResponse

**Comment by roc916** [comment]
https://github.com/essensoft/paylink/commit/3e07a03d654f567df752a0bf892785cf5f539804
