### ISSUE TITLE
同时支持微信公众号和微信小程序支付如何设置

### ISSUE THREAD

**Issue by billao** [essensoft/paylinks#162]
微信公众号和微信小程序的AppId是不同的，我看WeChatPayOptions只可以设置一个AppId，那在同一个应用实现微信公众号和微信小程序支付应该是如何设置？谢谢

**Comment by roc916** [comment]
https://github.com/essensoft/paylink/blob/68526515fed0f9a44d993b60675c77bf56d548e8/src/Essensoft.Paylink.WeChatPay/V3/IWeChatPayClient.cs#L14

你可以自己 new WeChatPayOptions(需要缓存，不要调用一次就new一次)，不必限缩在Sample。

**Comment by billao** [comment]
好的，谢谢！虽然稍为麻烦了点，不像配置那么方便。
