### ISSUE TITLE
关于微信支付平台收付通的相关咨询

### ISSUE THREAD

**Issue by ApiInk** [essensoft/paylinks#163]
作者是否考虑增加平台收付通中的相关功能，如商户进件、普通支付、合单支付等功能呢，腾讯官方文档地址如下：https://pay.weixin.qq.com/docs/partner/apis/ecommerce-merchant-application/applyment/submit-applyment.html

**Comment by roc916** [comment]
Paylink 具备一定的扩展性，建议参考 [WeChatPay/V3](https://github.com/essensoft/paylink/tree/dev/src/Essensoft.Paylink.WeChatPay/V3) 自行实现。
