### ISSUE TITLE
options.V3Key is Empty!

### ISSUE THREAD

**Issue by firechun** [essensoft/paylinks#165]
我是按照示例程序在appsetting.json中添加的APIv3Key，发送WeChatPayTransactionsJsApiRequest请求时报如题错误。

    // 商户APIv3密钥
    // 为微信支付商户平台的APIv3密钥，请注意不是API密钥，v3接口必填
    "APIv3Key": "我的v3密钥",

我在代码中强行设置了v3Key，调用成功。
                    optionsAccessor.Value.V3Key = "我的v3密钥";

**Comment by roc916** [comment]
https://github.com/essensoft/paylink/blob/68526515fed0f9a44d993b60675c77bf56d548e8/samples/WebApplicationSample/appsettings.Development.json#L11

**Comment by firechun** [comment]
是正式环境。

**Comment by roc916** [comment]
哪个版本？

**Comment by firechun** [comment]
通过nuget安装的，3.3.2
