### ISSUE TITLE
在abp使用微信V3扫码支付，支付结果通知接口，报错 Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.

### ISSUE THREAD

**Issue by weiveFf** [essensoft/paylinks#166]
![image](https://github.com/essensoft/paylink/assets/73087960/e8c6fd32-847d-4d07-b5b0-c2a43565b2d5)
报错信息：
 Unexpected end of request content.
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
options和Request我都看的传了 
其他接口是正常的

**Comment by roc916** [comment]
看起来是传入的Request有问题，你可以自行尝试获取下参数。

https://github.com/essensoft/paylink/blob/68526515fed0f9a44d993b60675c77bf56d548e8/src/Essensoft.Paylink.WeChatPay/V3/WeChatPayNotifyClient.cs#L45

**Comment by weiveFf** [comment]
我想问一下 这个Request不是HttpContext中的Request对象吗？ 为什么我拿不到Body呢
![image](https://github.com/essensoft/paylink/assets/73087960/d54b296c-d72e-4f4f-ba7d-b8c63f8dbe63)

**Comment by weiveFf** [comment]
![image](https://github.com/essensoft/paylink/assets/73087960/f1a17c1c-1db6-4937-80a2-8cfebfecbf44)
现在获取不到Body，是我使用的request的问题吗
