### ISSUE TITLE
在使用v3的通过商家明细单号查询明细单 接口时，发现错误。（WeChatPayTransferBatchesOutBatchNoDetailsOutDetailNoRequest ）

### ISSUE THREAD

**Issue by 154571895** [essensoft/paylinks#167]
当 WeChatPayTransferBatchesOutBatchNoDetailsOutDetailNoRequest 类中,WeChatPayObject 返回null时，在WeChatPayClient.EncryptPrivacyProperty  中加密时会出现 空对象引用的情况，麻烦您可以更新一下吗？
![1713171790310_E937A480-9B1F-4f1f-96C3-B3A5F08EB6A6](https://github.com/essensoft/paylink/assets/40639583/9f5bc5a1-0e05-43c4-babc-7d494d13310a)

**Comment by roc916** [comment]
https://github.com/essensoft/paylink/commit/2ca5ce0c950de21725731ce6ba522a19931d6c88
