### ISSUE TITLE
AlipayTradePageMergePayRequest   使用哪个回调通知呢

### ISSUE THREAD

**Issue by Aaron-Wei** [essensoft/paylinks#173]
请问AlipayTradePageMergePayRequest   使用哪个回调通知呢

AlipayTradePageMergePayResponse

**Comment by roc916** [comment]
都可以，比如: AlipayTradePrecreateNotify

**Comment by Aaron-Wei** [comment]
> AlipayTradePrecreateNotify
可是  AlipayTradePrecreateNotify  返回的结果  与  官方提供的并不相同  没有  子订单中所有订单的支付结果信息
![image](https://github.com/user-attachments/assets/080540c5-d4e0-4031-8da6-acf72a8dacec)

**Comment by roc916** [comment]
这是响应参数，对应的是AlipayTradePageMergePayResponse，并不是通知。

**Comment by Aaron-Wei** [comment]
明白了，感谢答疑，祝您工作和生活顺利
![image](https://github.com/user-attachments/assets/3e70cc63-6ca9-4ef8-8557-bb93907e2e5f)
