### ISSUE TITLE
新开通的微信商户号默认不开通平台证书了,推荐使用微信支付公钥,咱们的库有支持么

### ISSUE THREAD

**Issue by 2693587744** [essensoft/paylinks#181]
这是最近微信技术支持发来的消息:

微信新推出了平台证书的替代公钥方案，两者使用场景完全相同，但公钥不会过期，也就是以后没有特殊需求都不再需要人工管理
微信支付公钥使用介绍：https://pay.weixin.qq.com/docs/merchant/products/platform-certificate/wxp-pub-key-guide.html
平台证书切换微信支付公钥指引：https://pay.weixin.qq.com/docs/merchant/products/platform-certificate/update-pub-key.html

**Comment by roc916** [comment]
https://github.com/essensoft/paylink/commit/2e4976e5f29d1a3121e5150427ce1f6266129c7b
